# Petstore API
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: Example Petstore API (OpenAPI v3)
  tags:
    - openapi
    - example
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json

---

# Databricks Workspace API
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: databricks-workspace-api
  description: Databricks Workspace REST API
  tags:
    - databricks
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: data-platform-team
  definition: |
    openapi: 3.0.0
    info:
      title: Databricks Workspace API
      version: 1.0.0
      description: Databricks REST API example
    servers:
      - url: https://<your-databricks-instance>.cloud.databricks.com/api/2.0
    paths:
      /clusters/list:
        get:
          summary: List clusters
          security:
            - BearerAuth: []
          responses:
            '200':
              description: List of clusters
      /jobs/list:
        get:
          summary: List jobs
          security:
            - BearerAuth: []
          responses:
            '200':
              description: List of jobs
    components:
      securitySchemes:
        BearerAuth:
          type: http
          scheme: bearer
          bearerFormat: PAT