openapi: 3.0.0
info:
  title: Databricks Workspace API
  version: 1.0.0
  description: Databricks REST API example
servers:
  - url: https://<your-databricks-instance>.cloud.databricks.com/api/2.0
paths:
  /clusters/list:
    get:
      summary: List clusters
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of clusters
          content:
            application/json:
              schema:
                type: object
                properties:
                  clusters:
                    type: array
                    items:
                      type: object
                      properties:
                        cluster_id:
                          type: string
                        cluster_name:
                          type: string
  /jobs/list:
    get:
      summary: List jobs
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of jobs
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobs:
                    type: array
                    items:
                      type: object
                      properties:
                        job_id:
                          type: integer
                        name:
                          type: string
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: PAT